(()=>{
'use strict';
const $=id=>document.getElementById(id), f=$('appFrame'), dlg=$('captureDialog'), dz=$('captureDropZone'), fi=$('captureFile'), img=$('capturePreview'), pw=$('capturePreviewWrap'), box=$('detectedTasks'), head=$('captureResultHead'), count=$('captureResultCount'), prog=$('captureProgressWrap'), bar=$('captureProgressBar'), ptxt=$('captureProgressText'), imp=$('importDetectedBtn'), raw=$('rawOcrText'), notice=$('captureNotice'), fab=$('captureFab');
let found=[],run=0,obj='';
const verbs=['hablar','ver','mandar','enviar','armar','acordar','convocar','reunir','reunirme','preparar','pedir','revisar','coordinar','confirmar','solicitar','cargar','hacer','definir','analizar','chequear','proyectar','llamar','contactar','agregar','sumar','completar','obtener','presentar','consultar','resolver','crear','capacitar','planificar','organizar','evaluar','actualizar','corroborar','gestionar','seguir','dejar','tener','conseguir','buscar','aclarar','validar','programar','agendar','medir','comparar','informar','notificar','recordar','preguntar','cotizar','presupuestar','entregar'];
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const toast=m=>{try{f.contentWindow.toast?.(m)}catch{};};
function note(m,k='info'){notice.textContent=m;notice.className=`capture-notice ${k}`;notice.hidden=false;clearTimeout(note.t);note.t=setTimeout(()=>notice.hidden=true,5000)}
function open(){if(!dlg.open)dlg.showModal();setTimeout(()=>dz.focus(),0)}
function reset(close=false){run++;found=[];box.innerHTML='';head.hidden=true;imp.disabled=true;raw.value='';prog.hidden=true;bar.style.width='0%';fi.value='';pw.hidden=true;img.removeAttribute('src');if(obj)URL.revokeObjectURL(obj);obj='';if(close&&dlg.open)dlg.close()}
function clean(s){return String(s||'').replace(/[\u200B-\u200D\uFEFF]/g,'').trim().replace(/^\[?\s*\d{1,2}:\d{2}(?::\d{2})?\s*,?\s*\d{1,2}\/\d{1,2}\/\d{2,4}\s*\]?\s*[^:]{1,45}:\s*/i,'').replace(/^\s*(?:[-–—•·✓✔☐☑✅➡️]|\d{1,2}\s*[).:\-])\s*/,'').replace(/\s+/g,' ').replace(/^["“”']+|["“”']+$/g,'').trim()}
function action(s){const n=` ${norm(s)} `;return verbs.some(v=>n.includes(` ${norm(v)} `)||n.startsWith(` ${norm(v)} `))}
function noise(s){const n=norm(s).trim();return !n||n.length<4||/^(hoy|ayer|manana|whatsapp|buscar|tareas|mensajes|foto|captura|nueva tarea|filtros)$/.test(n)||/^\d{1,2}:\d{2}/.test(n)||/^https?:\/\//i.test(s)||/^[\d\s()+.\/-]+$/.test(n)}
function detect(text){const rows=String(text||'').split(/\r?\n/), out=[];for(const r of rows){const bullet=/^\s*(?:[-–—•·✓✔☐☑✅➡️]|\d{1,2}\s*[).:\-])/.test(r), s=clean(r);if(noise(s))continue;if(action(s)||bullet){out.push(s);continue}if(out.length&&s.length<100&&!/[.!?]$/.test(out[out.length-1])&&!action(s))out[out.length-1]+=' '+s}const seen=new Set();return out.map(clean).filter(s=>{const k=norm(s).replace(/[^a-z0-9]+/g,' ').trim();if(k.length<4||seen.has(k))return false;seen.add(k);return true}).slice(0,40)}
function area(title){try{return f.contentWindow.detectCategory?.(title,'','')||'Pedidos'}catch{return'Pedidos'}}
function render(lines){found=lines.map(x=>({title:x,selected:true}));head.hidden=false;refresh();if(!lines.length)box.innerHTML='<div class="capture-empty">No encontré tareas claras. Probá con una captura más nítida o recortada.</div>'}
function refresh(){count.textContent=found.length;box.innerHTML=found.map((t,i)=>`<div class="detected-task"><input class="detected-check" type="checkbox" data-i="${i}" ${t.selected?'checked':''}><div><input class="detected-title" data-i="${i}" value="${esc(t.title)}"><div class="detected-meta"><span>📁 ${esc(area(t.title))}</span><span>Estado inicial</span></div></div><button class="detected-remove" data-del="${i}" type="button">×</button></div>`).join('');imp.disabled=!found.some(t=>t.selected&&t.title.trim())}
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function progress(m){prog.hidden=false;const p=Math.round((m.progress||0)*100);bar.style.width=`${p}%`;const labels={'loading tesseract core':'Cargando lector…','initializing tesseract':'Iniciando lector…','loading language traineddata':'Cargando español…','initializing api':'Preparando lectura…','recognizing text':'Leyendo la captura…'};ptxt.textContent=`${labels[m.status]||'Analizando…'} ${p?p+'%':''}`}
async function read(file,lang,id){return Tesseract.recognize(file,lang,{logger:m=>id===run&&progress(m)})}
async function load(file){if(!file?.type?.startsWith('image/'))return note('Elegí una imagen o captura válida.','error');if(obj)URL.revokeObjectURL(obj);obj=URL.createObjectURL(file);img.src=obj;pw.hidden=false;found=[];box.innerHTML='';head.hidden=true;imp.disabled=true;raw.value='';const id=++run;prog.hidden=false;bar.style.width='4%';ptxt.textContent='Preparando lectura…';if(!window.Tesseract){prog.hidden=true;return note('No se pudo cargar el lector de capturas. Revisá la conexión.','error')}try{let r;try{r=await read(file,'spa',id)}catch(e){console.warn(e);if(id!==run)return;ptxt.textContent='Reintentando lectura…';r=await read(file,'eng',id)}if(id!==run)return;const text=r?.data?.text||'';raw.value=text.trim();const lines=detect(text);bar.style.width='100%';render(lines);setTimeout(()=>id===run&&(prog.hidden=true),400);const m=lines.length===1?'Detecté 1 tarea en la captura.':`Detecté ${lines.length} tareas en la captura.`;note(m+(lines.length?' Revisalas antes de crearlas.':''),lines.length?'success':'info');toast(`📸 ${m}`)}catch(e){console.error(e);if(id!==run)return;prog.hidden=true;render([]);note('No pude leer esa captura. Probá con una imagen más nítida o recortada.','error')}}
function paste(e){const file=[...(e.clipboardData?.items||[])].find(x=>x.type?.startsWith('image/'))?.getAsFile();if(!file)return;e.preventDefault();open();load(file)}
async function clip(){if(!navigator.clipboard?.read)return note('Usá Ctrl+V para pegar la captura.','info');try{for(const it of await navigator.clipboard.read()){const type=it.types.find(t=>t.startsWith('image/'));if(type){const b=await it.getType(type);return load(new File([b],`captura-${Date.now()}.${type.split('/')[1]||'png'}`,{type}))}}note('No encontré una imagen en el portapapeles.','info')}catch{note('El navegador no permitió leer el portapapeles. Usá Ctrl+V.','error')}}
function inject(){try{const d=f.contentDocument,w=f.contentWindow,t=d?.querySelector('.toolbar');if(!d||!w||!t)return false;if(!d.getElementById('captureTaskBtn')){const b=d.createElement('button');b.type='button';b.id='captureTaskBtn';b.className='btn';b.innerHTML='<i data-lucide="scan-text"></i> Desde captura';b.onclick=open;t.insertBefore(b,d.getElementById('newTaskBtn')||null)}if(!d.__capturePaste){d.addEventListener('paste',paste);d.__capturePaste=true}try{w.getNewTaskShortcutUrl=()=>{const u=new URL(location.href);u.search='';u.searchParams.set('nueva','1');u.hash='';return u.toString()}}catch{}w.refreshIcons?.();fab.hidden=true;return true}catch(e){console.warn(e);return false}}
async function importTasks(){const sel=found.filter(t=>t.selected&&t.title.trim());if(!sel.length)return;const w=f.contentWindow;if(!w?.getCanvasTasks)return note('El tablero todavía está cargando.','error');let status='urgente';try{status=w.getStatuses?.()[0]?.id||status}catch{}const created=sel.map(t=>({id:crypto.randomUUID?.()||`capture-${Date.now()}-${Math.random().toString(36).slice(2)}`,title:t.title.trim(),area:area(t.title),categoryMode:'auto',owner:'',deadline:'',recurrence:'none',recurrenceDay:null,status,substatus:'',priority:'media',description:'',attachments:[]}));const merged=[...(w.getCanvasTasks()||[]),...created];try{w.applyCanvasRemoteTasks?.(merged);if(typeof w.saveTasksCloudReady==='function')w.saveTasksCloudReady();else w.syncTasksToFirestore?.(merged)?.catch(console.error);w.queueReminderSync?.();const n=created.length;dlg.close();reset(false);toast(n===1?'📸 1 tarea detectada y creada':`📸 ${n} tareas detectadas y creadas`);note(n===1?'Se creó 1 tarea desde la captura.':`Se crearon ${n} tareas desde la captura.`,'success')}catch(e){console.error(e);note('Pude detectar las tareas, pero no guardarlas.','error')}}
box.addEventListener('input',e=>{const i=+e.target.dataset.i;if(e.target.matches('.detected-title')&&found[i]){found[i].title=e.target.value;imp.disabled=!found.some(t=>t.selected&&t.title.trim())}});box.addEventListener('change',e=>{const i=+e.target.dataset.i;if(e.target.matches('.detected-check')&&found[i]){found[i].selected=e.target.checked;imp.disabled=!found.some(t=>t.selected&&t.title.trim())}});box.addEventListener('click',e=>{const i=e.target.dataset.del;if(i!==undefined){found.splice(+i,1);refresh();if(!found.length)box.innerHTML='<div class="capture-empty">No quedan tareas seleccionadas.</div>'}});
$('chooseCaptureBtn').onclick=()=>fi.click();fi.onchange=()=>fi.files?.[0]&&load(fi.files[0]);$('clipboardCaptureBtn').onclick=clip;$('closeCaptureBtn').onclick=()=>dlg.close();$('clearCaptureBtn').onclick=()=>reset(false);imp.onclick=importTasks;fab.onclick=open;document.addEventListener('paste',paste);
['dragenter','dragover'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.add('dragging')}));['dragleave','drop'].forEach(x=>dz.addEventListener(x,e=>{e.preventDefault();dz.classList.remove('dragging')}));dz.addEventListener('drop',e=>{const x=[...(e.dataTransfer?.files||[])].find(x=>x.type.startsWith('image/'));if(x)load(x)});dz.onclick=e=>{if(!e.target.closest('button'))fi.click()};dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();fi.click()}};
f.addEventListener('load',()=>{let n=0;const timer=setInterval(()=>{if(inject()||++n>40)clearInterval(timer)},150)});const u=new URL('app.html',location.href);u.search=location.search;u.hash=location.hash;f.src=u.toString();
})();
